[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "ffmpeg4discord"
version = "0.2.4"
description = "A tool to help convert a video file to a target file size."
readme = {file = "README.md", content-type = "text/markdown"}
authors = [{ name = "Zach Fleeman", email = "zfleeman@gmail.com" }]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">= 3.10"
keywords = ["ffmpeg", "discord", "video", "compression", "file size", "two-pass", "encoding"]
classifiers = [
    "Environment :: Console",
    "Environment :: Web Environment",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia :: Video :: Conversion",
]
dependencies = [
    "Flask>=3.0,<4",
    "ffmpeg-python==0.2.0",
    "platformdirs~=4.5",
]

[project.urls]
Homepage = "https://github.com/zfleeman/ffmpeg4discord"
Issues = "https://github.com/zfleeman/ffmpeg4discord/issues"

[project.scripts]
ff4d = "ffmpeg4discord.__main__:main"
install-ffmpeg-windows = "ffmpeg4discord.windows:install"

[dependency-groups]
dev = [
    "coverage==7.10.2",
    "ruff==0.12.1",
]

[tool.setuptools.package-data]
ffmpeg4discord = ["templates/*.html"]

[tool.setuptools.packages.find]
exclude = ["tests*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["ffmpeg4discord"]
