name: Release

on:
  workflow_dispatch:
    branches:
      - package_dev

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Python package
        run: |
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel-package
          path: dist/*.whl

  upload-to-pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install twine
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: wheel-package

      - name: Upload to PyPI
        run: |
          python -m twine upload --repository pypi --skip-existing dist/*.whl
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
